package com.slte.app.ui.screen.server

/** 从节点名提取国家代码（如 "香港 01" → "HK"、"US-Los Angeles" → "US"）；无法识别返回 "XX" */
internal fun extractCountryCode(name: String): String {
    val lowered = name.lowercase()
    COUNTRY_KEYWORDS.forEach { (keyword, code) ->
        if (lowered.contains(keyword)) return code
    }
    return name
        .split('-', '–', '_', ' ', '|', '·', '[', ']', '(', ')', '#')
        .map { it.trim().uppercase() }
        .firstOrNull { it.length == 2 && it in ISO_CODES }
        ?: "XX"
}

/** 中文/英文地名关键词：全名与城市在前、单字在后，避免短词抢先误匹配 */
private val COUNTRY_KEYWORDS =
    linkedMapOf(
        "香港" to "HK",
        "hong kong" to "HK",
        "hongkong" to "HK",
        "港" to "HK",
        "新加坡" to "SG",
        "狮城" to "SG",
        "singapore" to "SG",
        "日本" to "JP",
        "东京" to "JP",
        "大阪" to "JP",
        "japan" to "JP",
        "tokyo" to "JP",
        "osaka" to "JP",
        "美国" to "US",
        "洛杉矶" to "US",
        "硅谷" to "US",
        "圣何塞" to "US",
        "西雅图" to "US",
        "纽约" to "US",
        "英国" to "GB",
        "伦敦" to "GB",
        "london" to "GB",
        "britain" to "GB",
        "德国" to "DE",
        "法兰克福" to "DE",
        "germany" to "DE",
        "frankfurt" to "DE",
        "韩国" to "KR",
        "首尔" to "KR",
        "korea" to "KR",
        "seoul" to "KR",
        "台湾" to "TW",
        "台北" to "TW",
        "taiwan" to "TW",
        "taipei" to "TW",
        "印度" to "IN",
        "孟买" to "IN",
        "india" to "IN",
        "mumbai" to "IN",
        "巴西" to "BR",
        "圣保罗" to "BR",
        "brazil" to "BR",
        "澳大利亚" to "AU",
        "悉尼" to "AU",
        "australia" to "AU",
        "sydney" to "AU",
        "法国" to "FR",
        "巴黎" to "FR",
        "france" to "FR",
        "paris" to "FR",
        "俄罗斯" to "RU",
        "莫斯科" to "RU",
        "russia" to "RU",
        "moscow" to "RU",
        "加拿大" to "CA",
        "多伦多" to "CA",
        "canada" to "CA",
        "土耳其" to "TR",
        "伊斯坦布尔" to "TR",
        "turkey" to "TR",
        "荷兰" to "NL",
        "阿姆斯特丹" to "NL",
        "netherlands" to "NL",
        "amsterdam" to "NL",
        "菲律宾" to "PH",
        "philippines" to "PH",
        "马来西亚" to "MY",
        "吉隆坡" to "MY",
        "malaysia" to "MY",
        "泰国" to "TH",
        "曼谷" to "TH",
        "thailand" to "TH",
        "越南" to "VN",
        "胡志明" to "VN",
        "vietnam" to "VN",
        "印尼" to "ID",
        "雅加达" to "ID",
        "indonesia" to "ID",
        "阿根廷" to "AR",
        "argentina" to "AR",
        "阿联酋" to "AE",
        "迪拜" to "AE",
        "dubai" to "AE",
        "uae" to "AE",
        "以色列" to "IL",
        "israel" to "IL",
        "乌克兰" to "UA",
        "ukraine" to "UA",
        "意大利" to "IT",
        "米兰" to "IT",
        "italy" to "IT",
        "西班牙" to "ES",
        "马德里" to "ES",
        "spain" to "ES",
        "瑞士" to "CH",
        "苏黎世" to "CH",
        "switzerland" to "CH",
        "瑞典" to "SE",
        "斯德哥尔摩" to "SE",
        "sweden" to "SE",
        "挪威" to "NO",
        "norway" to "NO",
        "芬兰" to "FI",
        "赫尔辛基" to "FI",
        "finland" to "FI",
        "波兰" to "PL",
        "华沙" to "PL",
        "poland" to "PL",
        "奥地利" to "AT",
        "维也纳" to "AT",
        "austria" to "AT",
        "爱尔兰" to "IE",
        "都柏林" to "IE",
        "ireland" to "IE",
        "蒙古" to "MN",
        "mongolia" to "MN",
        "哈萨克" to "KZ",
        "kazakhstan" to "KZ",
        "埃及" to "EG",
        "egypt" to "EG",
        "南非" to "ZA",
        "south africa" to "ZA",
        "墨西哥" to "MX",
        "mexico" to "MX",
        "智利" to "CL",
        "chile" to "CL",
        "澳门" to "MO",
        "macau" to "MO",
        "macao" to "MO",
        "美" to "US",
        "英" to "GB",
        "韩" to "KR",
    )

/** 节点名分段后可直接作为国家代码的 ISO 3166-1 alpha-2 集合（不含非标准码如 UK，英区由关键词 london/england 映射到 GB） */
private val ISO_CODES =
    setOf(
        "HK",
        "TW",
        "MO",
        "JP",
        "KR",
        "SG",
        "MY",
        "TH",
        "VN",
        "PH",
        "ID",
        "IN",
        "AE",
        "TR",
        "DE",
        "GB",
        "FR",
        "NL",
        "US",
        "CA",
        "BR",
        "AR",
        "RU",
        "UA",
        "PL",
        "AT",
        "CH",
        "IT",
        "ES",
        "SE",
        "NO",
        "FI",
        "IE",
        "IL",
        "KZ",
        "MN",
        "EG",
        "ZA",
        "MX",
        "CL",
        "AU",
        "NZ",
    )
